version: '3'
services:
  db:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=foodsquare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

# docker-compose up
