version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=foodsquare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432'
  web:
    image: subangkar/foodsquare
    command: sh -c "while ! nc -z db 5432; do sleep 1; done; ./startdatabase.sh && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db

# docker-compose up
# docker-compose run web python3 manage.py migrate