# Generated by Django 2.2.1 on 2019-06-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantImg',
            field=models.ImageField(default='restaurant_img/default.png', upload_to='restaurant_img/'),
        ),
    ]
