# Generated by Django 2.2.1 on 2019-07-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbranch',
            name='location_area',
            field=models.CharField(default='', max_length=50),
        ),
    ]
