# Generated by Django 2.2.1 on 2019-07-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190721_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='charge',
            field=models.FloatField(default=50, verbose_name='Delivery Fees'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='rating_deliveryman',
            field=models.IntegerField(null=True, verbose_name='Delivery Man Rating'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='rating_user',
            field=models.IntegerField(null=True, verbose_name='User Rating'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Delivery Completion Time'),
        ),
    ]
