# Generated by Django 2.2.1 on 2019-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurantbranch_location_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranch',
            name='branch_location_details',
            field=models.CharField(default='', max_length=100, verbose_name="If co-ordinates can't be provided or floor-no"),
        ),
    ]
