# Generated by Django 2.2.1 on 2019-07-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190721_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliveryman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DeliveryMan', verbose_name='Delivery Man'),
        ),
    ]
