# Generated by Django 2.2.1 on 2019-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190718_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=15, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Paid'), ('D', 'Due')], default='D', max_length=1, verbose_name='Payment Status'),
        ),
    ]
