# Generated by Django 2.2.1 on 2019-07-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190706_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranch',
            name='branch_location',
            field=models.CharField(default='0,0', max_length=50, verbose_name='Openstreetmap co-ordinates'),
        ),
    ]
