# Generated by Django 2.2.1 on 2019-07-06 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
        ('accounts', '0004_auto_20190706_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Delivery Address Description')),
                ('address_desc', models.CharField(max_length=50, verbose_name='Delivery Address Description')),
                ('charge', models.FloatField(verbose_name='Delivery Fees')),
                ('time', models.DateTimeField(verbose_name='Delivery Completion Time')),
                ('rating_user', models.IntegerField(verbose_name='User Rating')),
                ('rating_deliveryman', models.IntegerField(verbose_name='Delivery Man Rating')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('contactNum', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=50, verbose_name='Permanent Address')),
                ('nid', models.CharField(max_length=50, verbose_name='National ID No.')),
            ],
            options={
                'verbose_name': 'DeliveryMan',
                'verbose_name_plural': 'DeliveryMen',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Order Place Time')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Delivery', verbose_name='Person To Deliver')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Total Price')),
                ('payment_type', models.CharField(choices=[('C', 'Cash'), ('O', 'Online')], default='C', max_length=1, verbose_name='Payment Type')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='OrderPackageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Package', verbose_name='Package')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'OrderPackageList',
                'verbose_name_plural': 'OrderPackageLists',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Payment', verbose_name='Person To Deliver'),
        ),
        migrations.AddField(
            model_name='order',
            name='pkg_list',
            field=models.ManyToManyField(through='accounts.OrderPackageList', to='browse.Package', verbose_name='Packages in Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person To Deliver'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliveryman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DeliveryMan', verbose_name=''),
        ),
    ]
