# Generated by Django 2.2.1 on 2019-06-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190622_1425'),
        ('accounts', '0005_auto_20190617_1612'),
    ]

    operations = [
    ]
