# Generated by Django 2.2.1 on 2019-07-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190706_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpackagelist',
            old_name='delivery',
            new_name='package',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliveryman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DeliveryMan', verbose_name='Delivery Man'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Delivery', verbose_name='Delivery Info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Payment', verbose_name='Payment Info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Order Place Time'),
        ),
    ]
