# Generated by Django 2.2.1 on 2019-06-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20190623_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_key',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
