# Generated by Django 2.2.1 on 2019-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190706_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobileNo',
            field=models.CharField(default='0', max_length=15, verbose_name='Mobile Number'),
        ),
    ]
