# Generated by Django 2.2.1 on 2019-07-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_branch_manager',
            field=models.BooleanField(default=False, verbose_name='Manager Account'),
        ),
    ]
