# Generated by Django 2.2.1 on 2019-06-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190623_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
