# Generated by Django 2.2.1 on 2019-07-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.RestaurantBranch', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=15, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_branch_manager',
            field=models.BooleanField(default=False, verbose_name='Branch Manager Account'),
        ),
    ]
