# Generated by Django 2.2.1 on 2019-06-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190623_1216'),
        ('accounts', '0006_merge_20190623_0112'),
    ]

    operations = [
    ]
