# Generated by Django 2.2.1 on 2019-07-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190718_1909'),
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestBranch',
            fields=[
                ('restaurant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Restaurant')),
            ],
            bases=('accounts.restaurant',),
        ),
    ]
