# Generated by Django 2.2.1 on 2019-06-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_list',
        ),
        migrations.AddField(
            model_name='package',
            name='item_list',
            field=models.ManyToManyField(through='browse.ItemList', to='browse.Item'),
        ),
    ]
