# Generated by Django 2.2.1 on 2019-06-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20190618_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Ingredient')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Item')),
            ],
            options={
                'verbose_name': 'IngredientList',
                'verbose_name_plural': 'IngredientLists',
            },
        ),
    ]
