# Generated by Django 2.2.1 on 2019-07-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190718_1909'),
        ('browse', '0002_restbranch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestBranch',
        ),
    ]
