# Generated by Django 2.2.1 on 2019-06-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_auto_20190618_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingr_list',
            field=models.ManyToManyField(through='browse.IngredientList', to='browse.Ingredient'),
        ),
    ]
