# Generated by Django 2.2.1 on 2019-06-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_item_ingr_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingr_list',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='pkg_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='item_list',
        ),
        migrations.AddField(
            model_name='package',
            name='details',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='IngredientList',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
    ]
