# Generated by Django 2.2.1 on 2019-06-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_auto_20190619_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_contact_info',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='restaurant_id',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='package',
            name='restaurant_id',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
