# Generated by Django 2.2.1 on 2019-06-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_auto_20190619_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Restaurant'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
