# Generated by Django 2.2.1 on 2019-06-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0008_auto_20190622_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
    ]
