# Generated by Django 2.2.1 on 2019-06-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0009_remove_ingredient_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
