# Generated by Django 2.2.1 on 2019-06-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='men_name',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
