# Generated by Django 2.2.1 on 2019-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190614_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='men_name',
            new_name='menu_name',
        ),
    ]
